### ISSUE TITLE
Nova Resolução

### ISSUE THREAD

**Issue by CMS999** [CMS999/RiverNRaiders#9]
### Resolução e Escala

- Primeito: como trabalhamos com pixel art não precisamos oferecer multiplas resoluções para o jogo. Entretanto a resolução atual não entra nos padrões atuais de monitores (16:9 e 4:3). 
- Segundo: depois de alguns testes percebi que a arte está muito pequena na tela (640x320). Para comparação no strike gunner a nave é 15 vezes menor que a tela e no nosso jogo ela é 40 vezes menor.
- Terceiro: escalar/aumetar a arte funciona mas só para valores inteiros. Portanto, não podemos aumentar em 50% só em 100%, 200%, etc.

**Comment by Vincentius004** [comment]
Sim, mudemos a resolução. Mas qual o plano? Qual a resolução em mente, e como teriamos que rescalar os objetos na tela para funcionar?

**Comment by CMS999** [comment]
> Sim, mudemos a resolução. Mas qual o plano? Qual a resolução em mente, e como teriamos que rescalar os objetos na tela para funcionar?

Sim, esse é o problema não tenho certeza. Minha ideia era mudar para 640x360, para ser 16:9, e dobrar todos os sprites, ficando 32x32, a nave por exemplo ficaria apenas 20 menor que a tela nessa configuração. Mas não sei o quão viável é isso.

**Comment by Vincentius004** [comment]
Se for questão de codificar isso, é bem fácil (mexi no jogador em tipo 1 minuto), em questão de aparência eu diria que ficou até aceitável. Se for questão de fazer sprites maiores, aí tem que ver com o Fernando mesmo. A propósito, enquanto eu mexia nisso, eu eu percebi um bug visual no jogador, é bem pequeno, mas ficaria perceptível em resoluções maiores.

**Comment by CMS999** [comment]
> Se for questão de codificar isso, é bem fácil (mexi no jogador em tipo 1 minuto), em questão de aparência eu diria que ficou até aceitável. Se for questão de fazer sprites maiores, aí tem que ver com o Fernando mesmo. A propósito, enquanto eu mexia nisso, eu eu percebi um bug visual no jogador, é bem pequeno, mas ficaria perceptível em resoluções maiores.

Minha preocupação é estética e gameplay apenas. Escalar artes menores para tamanhos maiores pode não ter um bom resultado e meu sentimento testando a fase com o tamanho atual, foi de que o jogador demora muito para cruzar a tela e que há muito espaço para desviar de projéteis.

**Comment by Vincentius004** [comment]
![image](https://github.com/CMS999/RiverNRaiders/assets/56077081/78f7958d-3f97-42d9-850b-886c5ad3d34f)
(Testando pra ver se mandar assim funciona)

Eu dobrei o tamanho do player, e ele ficou assim.

**Comment by Vincentius004** [comment]
OK, quando tiver terminado o seu teste a gente volta pra esse issue.

**Comment by CMS999** [comment]
@Vincentius004 Subi uma versão para teste na minha brench.

**Comment by Vincentius004** [comment]
@CMS999 Sem os inimigos acho que não fica tão bom pra testar, outra coisa é que não sei se full screen sem chance de mudar tbm n me parece uma boa ideia. Por último, parece que os "tiros" do missil ficaram super pixelados nessa alteração, vc mexeu algo neles?

**Comment by CMS999** [comment]
> @CMS999 Sem os inimigos acho que não fica tão bom pra testar, outra coisa é que não sei se full screen sem chance de mudar tbm n me parece uma boa ideia. Por último, parece que os "tiros" do missil ficaram super pixelados nessa alteração, vc mexeu algo neles?

Era pra ter os inimigos, no meu aqui tem. Está fullscreen porque eu estava testanto a resolução. Os tiros não foram alterados.

**Comment by Vincentius004** [comment]
> > @CMS999 Sem os inimigos acho que não fica tão bom pra testar, outra coisa é que não sei se full screen sem chance de mudar tbm n me parece uma boa ideia. Por último, parece que os "tiros" do missil ficaram super pixelados nessa alteração, vc mexeu algo neles?
> 
> Era pra ter os inimigos, no meu aqui tem. Está fullscreen porque eu estava testanto a resolução. Os tiros não foram alterados.
Quando eu mudo pra sua branch, o git fica dizendo que tem mudanças locais nos arquivos, sendo que eu só tentei rodar. Dei pull em tudo, diz que tá atualizado, e os inimigos não aparecem do mesmo jeito.

**Comment by CMS999** [comment]
@Vincentius004 
### Nova Ideia
Mudar a resolução para 320x180, metade do proposto, tera o mesmo efeito do que escalar tudo por 2, sem precisar comprometer a arte original.

**Comment by CMS999** [comment]
> @Vincentius004
> 
> ### Nova Ideia
> Mudar a resolução para 320x180, metade do proposto, tera o mesmo efeito do que escalar tudo por 2, sem precisar comprometer a arte original.

Subi uma nova versão de teste, com a mudança proposta. Na minha branch.

**Comment by CMS999** [comment]
Issue resolve
